### ISSUE TITLE
Unsatisfactory results using demo code

### ISSUE THREAD

**Issue by ArchHazel** [idiap/ESLAM#12]
Thank you so much for your awesome work! 

I installed your repo on WSL2 and docker, and my GPU is 3090. I haven't seen any errors during training.

After running the code, I was so confused why the reconstructed results on TUM (freiburg1_desk) and ScanNet (Scene0000_00) is not satisfactory. I was using the provided config files without making any changes. 

Here is the culled mesh of Freiburg1_desk:
![image](https://github.com/idiap/ESLAM/assets/68803880/f8615508-d5a1-4b41-ab36-6bcc5074dc99)
As you can see, it appears like a tetrahedron without no details inside.

The same issue is observed with Scannet:
![image](https://github.com/idiap/ESLAM/assets/68803880/47d92ed7-b594-4aa8-8fa3-01b986780a12)

Could you please provide guidance on how to troubleshoot the issue?

**Comment by MohammadJohari** [comment]
Hello,

Unfortunately, it is very difficult to debug this issue with the provided amount of information. Could you please set the `vis_freq` to something like 40 and see if the intermediate rendered images have meaningful values or not. This would at least clarifies the issue is within the learning process or the mesh extraction algorithm.

Kind regards,
